# This message defines meta information for a panorama image.

#######################################################################
#                     Image acquisition info                          #
#######################################################################
std_msgs/Header header

#######################################################################
#                     Field of View Parameters                         #
#######################################################################
float64 theta_min
float64 theta_max
float64 phi_min
float64 phi_max
